version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:$IMAGE_VERSION
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000   
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s  

  kafka:
    image: confluentinc/cp-kafka:$IMAGE_VERSION
    container_name: kafka1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "19092:19092"      
    networks:
      - kafka_network      
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,PLAINTEXT://kafka1:9093,OUTSIDE://$HOST_IP:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  control-center:
    image: confluentinc/cp-enterprise-control-center:$IMAGE_VERSION
    container_name: control-center
    depends_on:
      - kafka
      - zookeeper
    environment:
      CONTROL_CENTER_KAFKA_BROKER: PLAINTEXT://kafka1:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka1:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_CONNECT_CLUSTER: "kafka1:9092"
      CONTROL_CENTER_DATA_TOPICS_AUTO_CREATE: "false"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    ports:
      - "9021:9021"
    networks:
      - kafka_network      

  schema-registry:
    image: confluentinc/cp-schema-registry:$IMAGE_VERSION
    hostname: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    networks:
      - kafka_network        
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: INTERNAL://kafka1:9092,PLAINTEXT://kafka1:9093,OUTSIDE://$HOST_IP:19092
      SCHEMA_REGISTRY_DEBUG: 'true'

networks:
  kafka_network:
    driver: bridge