version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${IMAGE_VERSION}
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"    

  kafka:
    image: confluentinc/cp-kafka:${IMAGE_VERSION}
    container_name: kafka1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,PLAINTEXT://kafka1:9093,OUTSIDE://${HOST_IP}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9094:9094"
      - "9093:9093"      
      - "9092:9092"

  control-center:
    image: confluentinc/cp-enterprise-control-center:${IMAGE_VERSION}
    container_name: control-center
    depends_on:
      - kafka
      - zookeeper
    environment:
      CONTROL_CENTER_KAFKA_BROKER: PLAINTEXT://kafka1:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka1:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_CONNECT_CLUSTER: "kafka1:9092"
      CONTROL_CENTER_DATA_TOPICS_AUTO_CREATE: "false"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    ports:
      - "9021:9021"

  schema-registry:
    image: confluentinc/cp-schema-registry:${IMAGE_VERSION}
    hostname: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: INTERNAL://kafka1:9092,OUTSIDE://${HOST_IP}:9094,PLAINTEXT://kafka1:9093
      SCHEMA_REGISTRY_DEBUG: 'true'      