version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:$IMAGE_VERSION
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000   
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  kafka1:
    image: confluentinc/cp-kafka:$IMAGE_VERSION
    container_name: kafka1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "19092:19092"   
    networks:
      - kafka_network         
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,PLAINTEXT://kafka1:9093,OUTSIDE://$HOST_IP:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka2:
    image: confluentinc/cp-kafka:$IMAGE_VERSION
    container_name: kafka2
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"      
    networks:
      - kafka_network   
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,PLAINTEXT://kafka2:9093,OUTSIDE://$HOST_IP:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka3:
    image: confluentinc/cp-kafka:$IMAGE_VERSION
    container_name: kafka3
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "39092:39092"      
    networks:
      - kafka_network      
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:39092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9092,PLAINTEXT://kafka3:9093,OUTSIDE://$HOST_IP:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  control-center:
    image: confluentinc/cp-enterprise-control-center:$IMAGE_VERSION
    container_name: control-center
    depends_on:
      - schema-registry
      - kafka1
      - kafka2
      - kafka3
      - zookeeper 
    ports:
      - "9021:9021"
    networks:
      - kafka_network          
    environment:
      CONTROL_CENTER_KAFKA_BROKER: PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9092,PLAINTEXT://kafka3:9092
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_CONNECT_KAFKA-CONNECT_CLUSTER: http://kafka-connect:8083
      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: /connectors
      CONTROL_CENTER_DATA_TOPICS_AUTO_CREATE: "false"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONTROL_CENTER_REPLICATION_FACTOR: 3
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 3

  kafka-rest:
    image: confluentinc/cp-kafka-rest:$IMAGE_VERSION
    container_name: rest-proxy
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - kafka_network
    environment:      
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081

  kafka-connect:
    container_name: kafka-connect
    image: confluentinc/cp-kafka-connect:$IMAGE_VERSION
    depends_on:
      - schema-registry
      - kafka1
      - kafka2
      - kafka3
      - zookeeper    
    ports:
      - "8083:8083"
    networks:
      - kafka_network
    environment:
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
      CONNECT_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_LISTENERS: http://0.0.0.0:8083
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'true'
      CONNECT_KEY_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'true'
      CONNECT_VALUE_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_PLUGIN_PATH: ' /usr/share/java/'

  schema-registry:
    image: confluentinc/cp-schema-registry:$IMAGE_VERSION
    hostname: schema-registry
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper
    ports:
      - "8081:8081"
    networks:
      - kafka_network
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: INTERNAL://kafka1:9092,PLAINTEXT://kafka1:9093,OUTSIDE://$HOST_IP:19092
      SCHEMA_REGISTRY_DEBUG: 'true'

networks:
  kafka_network:
    driver: bridge
